import { MigrationInterface, QueryRunner } from "typeorm";

export class AddDeletedAtColumns1768494672978 implements MigrationInterface {
    name = 'AddDeletedAtColumns1768494672978'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb731b6c9ec3271068b48a0786"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f160d97a931844109de9d04228"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_02cb32c3fa9ecfdb98ebe830c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7421efc125d95e413657efa3c6"`);
        await queryRunner.query(`CREATE TABLE "webhook_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying, "name" character varying NOT NULL, "url" character varying NOT NULL, "description" character varying, "secret" character varying NOT NULL, "events" text NOT NULL, "active" boolean NOT NULL DEFAULT true, "failureCount" integer NOT NULL DEFAULT '0', "lastFailureAt" TIMESTAMP, "lastSuccessAt" TIMESTAMP, "lastError" character varying, "maxRetries" integer NOT NULL DEFAULT '3', "timeoutMs" integer NOT NULL DEFAULT '30000', "headers" jsonb, "verifySSL" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, CONSTRAINT "PK_bf631ae77d39849d599817fb6f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_edff27c4b8b6310a65ab737044" ON "webhook_subscriptions" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_00ac264c8f30c169de20af863a" ON "webhook_subscriptions" ("url") `);
        await queryRunner.query(`CREATE INDEX "IDX_26f69fd43ee6cf047a3db9383b" ON "webhook_subscriptions" ("tenantId", "active") `);
        await queryRunner.query(`CREATE TYPE "public"."webhook_delivery_logs_eventtype_enum" AS ENUM('alert.created', 'alert.updated', 'alert.resolved', 'task.created', 'task.assigned', 'task.started', 'task.completed', 'task.cancelled', 'resource.low', 'resource.depleted', 'resource.restocked', 'volunteer.checkin', 'volunteer.checkout', 'volunteer.dispatch', 'mission.started', 'mission.ended', 'mission.escalated', 'system.alert', 'sync.completed', '*')`);
        await queryRunner.query(`CREATE TYPE "public"."webhook_delivery_logs_status_enum" AS ENUM('pending', 'success', 'failed', 'retrying')`);
        await queryRunner.query(`CREATE TABLE "webhook_delivery_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscriptionId" uuid NOT NULL, "eventType" "public"."webhook_delivery_logs_eventtype_enum" NOT NULL, "payload" jsonb NOT NULL, "status" "public"."webhook_delivery_logs_status_enum" NOT NULL DEFAULT 'pending', "responseStatus" integer, "responseBody" text, "attempt" integer NOT NULL DEFAULT '0', "error" character varying, "durationMs" integer, "nextRetryAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "deliveredAt" TIMESTAMP, CONSTRAINT "PK_0e3b1d3f1b9b79d4a7ad0b92b84" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5211de203520b0ec8cd59d8448" ON "webhook_delivery_logs" ("subscriptionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3374e38e3e938a556545e94f22" ON "webhook_delivery_logs" ("eventType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc0ae1b4cd004209c02b5854da" ON "webhook_delivery_logs" ("subscriptionId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "shifts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" date NOT NULL, "templateId" character varying(50) NOT NULL, "volunteerId" character varying NOT NULL, "volunteerName" character varying(100) NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'scheduled', "notes" text, "locationId" character varying(100), "locationName" character varying(200), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_01a43905fce3aabc2d113840bc" ON "shifts" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_f20c3d3d0276a1f5ab2f73ca1c" ON "shifts" ("volunteerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d30bd3a69074dbb9c06cab694" ON "shifts" ("volunteerId", "date") `);
        await queryRunner.query(`CREATE TABLE "shift_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "color" character varying(7) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5afc978e7951d5bb48dcddc7a33" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payroll_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "volunteerId" character varying NOT NULL, "volunteerName" character varying(100) NOT NULL, "year" integer NOT NULL, "month" integer NOT NULL, "shiftCount" integer NOT NULL DEFAULT '0', "totalHours" numeric(6,2) NOT NULL DEFAULT '0', "basePay" numeric(10,2) NOT NULL DEFAULT '0', "nightBonus" numeric(10,2) NOT NULL DEFAULT '0', "holidayBonus" numeric(10,2) NOT NULL DEFAULT '0', "hazardBonus" numeric(10,2) NOT NULL DEFAULT '0', "transportAllowance" numeric(10,2) NOT NULL DEFAULT '0', "mealAllowance" numeric(10,2) NOT NULL DEFAULT '0', "otherAllowance" numeric(10,2) NOT NULL DEFAULT '0', "deductions" numeric(10,2) NOT NULL DEFAULT '0', "total" numeric(10,2) NOT NULL DEFAULT '0', "status" character varying(20) NOT NULL DEFAULT 'pending', "approvedAt" date, "approvedBy" character varying(100), "paidAt" date, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_869cabe268deb5726e742f2d3f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0ccbaa36d7ecf1b8017ebdf91a" ON "payroll_records" ("volunteerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b094ca83bdfa680b7073fd79cb" ON "payroll_records" ("volunteerId", "year", "month") `);
        await queryRunner.query(`CREATE TABLE "org_nodes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "type" character varying(50) NOT NULL, "parentId" uuid, "managerId" character varying(100), "managerName" character varying(100), "memberCount" integer NOT NULL DEFAULT '0', "sortOrder" integer NOT NULL DEFAULT '0', "description" character varying(200), "code" character varying(50), "isActive" boolean NOT NULL DEFAULT true, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_89534649e957a341d82ed3572b1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bff5096eb13f271ea37d2ef859" ON "org_nodes" ("parentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bff5096eb13f271ea37d2ef859" ON "org_nodes" ("parentId") `);
        await queryRunner.query(`CREATE TYPE "public"."command_chain_role_enum" AS ENUM('incident_commander', 'deputy_ic', 'safety_officer', 'public_info_officer', 'liaison_officer', 'operations_chief', 'planning_chief', 'logistics_chief', 'finance_admin_chief', 'division_supervisor', 'group_supervisor', 'branch_director', 'resources_unit_leader', 'situation_unit_leader', 'communications_unit_leader', 'medical_unit_leader', 'food_unit_leader')`);
        await queryRunner.query(`CREATE TYPE "public"."command_chain_status_enum" AS ENUM('assigned', 'active', 'relieved', 'standby')`);
        await queryRunner.query(`CREATE TABLE "command_chain" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "mission_session_id" uuid NOT NULL, "role" "public"."command_chain_role_enum" NOT NULL, "user_id" character varying NOT NULL, "user_name" character varying NOT NULL, "contact_phone" character varying, "contact_radio" character varying, "status" "public"."command_chain_status_enum" NOT NULL DEFAULT 'assigned', "reports_to_id" uuid, "assigned_by" character varying NOT NULL, "assigned_at" TIMESTAMP WITH TIME ZONE NOT NULL, "relieved_by" character varying, "relieved_at" TIMESTAMP WITH TIME ZONE, "relief_notes" text, "operational_period_id" uuid, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_14d6a6b171b66aad82fe6560a91" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_29fb3f50a71ea5942728fd59aa" ON "command_chain" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_517c45ca46263b843563aad2a9" ON "command_chain" ("mission_session_id", "role") `);
        await queryRunner.query(`CREATE TABLE "attendance_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "volunteerId" character varying NOT NULL, "date" date NOT NULL, "checkInTime" TIME NOT NULL, "checkOutTime" TIME, "hours" numeric(4,2), "method" character varying(10) NOT NULL, "checkInLat" numeric(10,6), "checkInLng" numeric(10,6), "checkOutLat" numeric(10,6), "checkOutLng" numeric(10,6), "locationName" character varying(100), "status" character varying(20) NOT NULL DEFAULT 'completed', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_946920332f5bc9efad3f3023b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_caeb65d7263e754c5f55d70260" ON "attendance_records" ("volunteerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a66518f5a16afacc50a845aa6b" ON "attendance_records" ("volunteerId", "date") `);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "previousState"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "newState"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "durationMs"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "success"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "userName"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "resourceType"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "resourceId"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "ipAddress"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "errorMessage"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "mission_session_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "before_snapshot"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "after_snapshot"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "ip_address"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "actor_user_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "actor_name"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_type"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_agent"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_caeb65d7263e754c5f55d70260"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "volunteerId"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "checkInTime"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "checkOutTime"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "hours"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "checkInLat"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "checkInLng"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "checkOutLat"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "checkOutLng"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "locationName"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "volunteers" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "mission_sessions" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "dispatch_tasks" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "actor_user_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "actor_name" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_type" character varying(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "mission_session_id" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "before_snapshot" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "after_snapshot" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "ip_address" inet`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_agent" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "userId" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "userName" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "resourceType" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "resourceId" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "previousState" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "newState" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "ipAddress" character varying(45)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "userAgent" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "requestId" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "durationMs" integer`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "success" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "errorMessage" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "volunteerId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "checkInTime" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "checkOutTime" TIME`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "hours" numeric(4,2)`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "checkInLat" numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "checkInLng" numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "checkOutLat" numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "checkOutLng" numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "locationName" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "status" character varying(20) NOT NULL DEFAULT 'completed'`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "volunteer_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "volunteer_name" character varying`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "task_id" uuid`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "mission_session_id" uuid`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "check_in_time" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "check_out_time" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "check_in_location" jsonb`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "check_out_location" jsonb`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "hours_worked" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_f160d97a931844109de9d04228" ON "audit_logs" ("actor_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_02cb32c3fa9ecfdb98ebe830c2" ON "audit_logs" ("mission_session_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7421efc125d95e413657efa3c6" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb731b6c9ec3271068b48a0786" ON "audit_logs" ("resourceType") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_caeb65d7263e754c5f55d70260" ON "attendance_records" ("volunteerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_763ae27d5eff963e3f77978a49" ON "attendance_records" ("mission_session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c7085b8f7a96fdff8dba82b7a8" ON "attendance_records" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_57c490427a74d6447eb4934f64" ON "attendance_records" ("volunteer_id", "check_in_time") `);
        await queryRunner.query(`ALTER TABLE "webhook_delivery_logs" ADD CONSTRAINT "FK_5211de203520b0ec8cd59d84489" FOREIGN KEY ("subscriptionId") REFERENCES "webhook_subscriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "command_chain" ADD CONSTRAINT "FK_d356a672cfd6e84070402f2b29f" FOREIGN KEY ("mission_session_id") REFERENCES "mission_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "command_chain" ADD CONSTRAINT "FK_b69e299ddb942cc86e5cf83d350" FOREIGN KEY ("reports_to_id") REFERENCES "command_chain"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "command_chain" DROP CONSTRAINT "FK_b69e299ddb942cc86e5cf83d350"`);
        await queryRunner.query(`ALTER TABLE "command_chain" DROP CONSTRAINT "FK_d356a672cfd6e84070402f2b29f"`);
        await queryRunner.query(`ALTER TABLE "webhook_delivery_logs" DROP CONSTRAINT "FK_5211de203520b0ec8cd59d84489"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57c490427a74d6447eb4934f64"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c7085b8f7a96fdff8dba82b7a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_763ae27d5eff963e3f77978a49"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_caeb65d7263e754c5f55d70260"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb731b6c9ec3271068b48a0786"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7421efc125d95e413657efa3c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_02cb32c3fa9ecfdb98ebe830c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f160d97a931844109de9d04228"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "hours_worked"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "check_out_location"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "check_in_location"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "check_out_time"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "check_in_time"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "mission_session_id"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "task_id"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "volunteer_name"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "volunteer_id"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "locationName"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "checkOutLng"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "checkOutLat"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "checkInLng"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "checkInLat"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "hours"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "checkOutTime"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "checkInTime"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP COLUMN "volunteerId"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "errorMessage"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "success"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "durationMs"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "ipAddress"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "newState"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "previousState"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "resourceId"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "resourceType"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "userName"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "ip_address"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "after_snapshot"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "before_snapshot"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "mission_session_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_type"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "actor_name"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "actor_user_id"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "dispatch_tasks" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "mission_sessions" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "volunteers" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "status" character varying(20) NOT NULL DEFAULT 'completed'`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "locationName" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "checkOutLng" numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "checkOutLat" numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "checkInLng" numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "checkInLat" numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "hours" numeric(4,2)`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "checkOutTime" TIME`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "checkInTime" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD "volunteerId" character varying NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_caeb65d7263e754c5f55d70260" ON "attendance_records" ("volunteerId") `);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_agent" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_type" character varying(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "actor_name" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "actor_user_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "ip_address" inet`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "after_snapshot" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "before_snapshot" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "mission_session_id" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "errorMessage" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "requestId" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "userAgent" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "ipAddress" character varying(45)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "resourceId" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "resourceType" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "userName" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "userId" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "success" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "durationMs" integer`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "newState" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "previousState" jsonb`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a66518f5a16afacc50a845aa6b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_caeb65d7263e754c5f55d70260"`);
        await queryRunner.query(`DROP TABLE "attendance_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_517c45ca46263b843563aad2a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29fb3f50a71ea5942728fd59aa"`);
        await queryRunner.query(`DROP TABLE "command_chain"`);
        await queryRunner.query(`DROP TYPE "public"."command_chain_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."command_chain_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bff5096eb13f271ea37d2ef859"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bff5096eb13f271ea37d2ef859"`);
        await queryRunner.query(`DROP TABLE "org_nodes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b094ca83bdfa680b7073fd79cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ccbaa36d7ecf1b8017ebdf91a"`);
        await queryRunner.query(`DROP TABLE "payroll_records"`);
        await queryRunner.query(`DROP TABLE "shift_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d30bd3a69074dbb9c06cab694"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f20c3d3d0276a1f5ab2f73ca1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01a43905fce3aabc2d113840bc"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc0ae1b4cd004209c02b5854da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3374e38e3e938a556545e94f22"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5211de203520b0ec8cd59d8448"`);
        await queryRunner.query(`DROP TABLE "webhook_delivery_logs"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_delivery_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_delivery_logs_eventtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26f69fd43ee6cf047a3db9383b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_00ac264c8f30c169de20af863a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_edff27c4b8b6310a65ab737044"`);
        await queryRunner.query(`DROP TABLE "webhook_subscriptions"`);
        await queryRunner.query(`CREATE INDEX "IDX_7421efc125d95e413657efa3c6" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_02cb32c3fa9ecfdb98ebe830c2" ON "audit_logs" ("mission_session_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f160d97a931844109de9d04228" ON "audit_logs" ("actor_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb731b6c9ec3271068b48a0786" ON "audit_logs" ("resourceType") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
    }

}
