<#
.SYNOPSIS
    Generate/update Summary Statistics in docs/proof/traceability.md
.DESCRIPTION
    Parses the Requirements Table in traceability.md and regenerates
    the Summary Statistics section to match actual row counts.
    Exits with code 1 if computed stats don't match (drift detection).
.OUTPUTS
    Updates docs/proof/traceability.md
.EXAMPLE
    pwsh tools/audit/generate-traceability.ps1
#>

param(
    [string]$RootDir = (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
)

$ErrorActionPreference = "Stop"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Generate Traceability Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Paths
$TraceabilityPath = Join-Path $RootDir "docs/proof/traceability.md"
$GateSummaryPath = Join-Path $RootDir "docs/proof/gates/gate-summary.json"

# Get git info (PS 5.1 compatible)
$gitCommit = git -C $RootDir rev-parse HEAD 2>$null
$commitSha = if ($gitCommit) { $gitCommit } else { "unknown" }
$gitBranch = git -C $RootDir rev-parse --abbrev-ref HEAD 2>$null
$branch = if ($gitBranch) { $gitBranch } else { "unknown" }
$gitUrl = git -C $RootDir remote get-url origin 2>$null
$repoUrl = if ($gitUrl) { $gitUrl } else { "unknown" }
$timestamp = (Get-Date).ToString("yyyy-MM-ddTHH:mm:sszzz")

# Load gate summary if available
$gateSummary = $null
if (Test-Path $GateSummaryPath) {
    try {
        $gateSummary = Get-Content $GateSummaryPath -Raw | ConvertFrom-Json
    }
    catch {
        Write-Host "  ⚠️  Failed to parse gate-summary.json" -ForegroundColor Yellow
    }
}

# Read existing traceability.md if exists
$existingContent = ""
if (Test-Path $TraceabilityPath) {
    $existingContent = Get-Content $TraceabilityPath -Raw
}

# Parse status counts from table rows (look for emoji patterns)
function Get-StatusCounts {
    param([string]$Content, [string]$Domain)
    
    $counts = @{
        PASS    = 0
        FAIL    = 0
        PENDING = 0
        BLOCKED = 0
    }
    
    # Find the domain section
    $domainPattern = "### Domain: $Domain"
    $domainStart = $Content.IndexOf($domainPattern)
    if ($domainStart -lt 0) { return $counts }
    
    # Find next domain or end
    $nextDomainPattern = "### Domain:"
    $domainEnd = $Content.IndexOf($nextDomainPattern, $domainStart + $domainPattern.Length)
    if ($domainEnd -lt 0) { $domainEnd = $Content.Length }
    
    $domainContent = $Content.Substring($domainStart, $domainEnd - $domainStart)
    
    # Count status markers in table rows
    $counts.PASS = ([regex]::Matches($domainContent, '✅ PASS')).Count
    $counts.FAIL = ([regex]::Matches($domainContent, '❌ FAIL')).Count
    $counts.PENDING = ([regex]::Matches($domainContent, '⏳ PENDING')).Count
    $counts.BLOCKED = ([regex]::Matches($domainContent, '🔴 BLOCKED')).Count
    
    return $counts
}

# Domains to scan
$domains = @("ICS/C2", "Security", "Deprecation")
$domainStats = @{}
$totals = @{ PASS = 0; FAIL = 0; PENDING = 0; BLOCKED = 0 }

foreach ($domain in $domains) {
    $counts = Get-StatusCounts -Content $existingContent -Domain $domain
    $domainStats[$domain] = $counts
    $totals.PASS += $counts.PASS
    $totals.FAIL += $counts.FAIL
    $totals.PENDING += $counts.PENDING
    $totals.BLOCKED += $counts.BLOCKED
}

$totalReqs = $totals.PASS + $totals.FAIL + $totals.PENDING + $totals.BLOCKED

Write-Host "Parsed requirements:" -ForegroundColor Yellow
Write-Host "  Total: $totalReqs" -ForegroundColor White
Write-Host "  PASS: $($totals.PASS) | FAIL: $($totals.FAIL) | PENDING: $($totals.PENDING) | BLOCKED: $($totals.BLOCKED)" -ForegroundColor White
foreach ($domain in $domains) {
    $d = $domainStats[$domain]
    Write-Host "  $domain`: PASS $($d.PASS) / PENDING $($d.PENDING) / FAIL $($d.FAIL) / BLOCKED $($d.BLOCKED)" -ForegroundColor DarkGray
}

# Generate new traceability.md content
$traceabilityContent = @"
<!--
FILE: docs/proof/traceability.md
PURPOSE: Requirement-to-Evidence Traceability Matrix (RTM). MUST be internally consistent; summary must be generated.
POLICY: Each row MUST include ReqID, source, tasks, commit, evidence paths, status.
GENERATED BY: tools/audit/generate-traceability.ps1
-->

# Traceability Matrix (RTM) — Light Keepers
> This matrix maps requirements to implementation tasks and evidence artifacts.  
> Hard rule: Any PASS claim without E2/E3 evidence (unless explicitly N/A) is invalid.

---

## Build Identity (Required)
- Repo: ``$repoUrl``
- Branch/Ref: ``$branch``
- Commit SHA: ``$commitSha``
- GeneratedAt (ISO8601): ``$timestamp``
- Generator: ``tools/audit/generate-traceability.ps1@1.0.0``

---

## Legend (Hard)

### Requirement Status (Row-level)
- **PASS**: Verified by evidence (E2/E3 required unless explicitly N/A).
- **FAIL**: Verified and failing; remediation required.
- **PENDING**: Implemented and/or planned but not evidenced.
- **BLOCKED**: Cannot verify due to environment; must state reason + next action.

### Pipeline Status (Task-level)
- IMPLEMENTED / VERIFIED / COMPLETE / BLOCKED / FAIL (must match ``docs/proof/index.md``)

---

## Summary Statistics (AUTO-DERIVED — DO NOT EDIT)
> Source of truth: computed from rows below.

- Total requirements: ``$totalReqs``
- PASS: ``$($totals.PASS)`` | FAIL: ``$($totals.FAIL)`` | PENDING: ``$($totals.PENDING)`` | BLOCKED: ``$($totals.BLOCKED)``
- By domain:
  - ICS/C2: PASS ``$($domainStats['ICS/C2'].PASS)`` / PENDING ``$($domainStats['ICS/C2'].PENDING)`` / FAIL ``$($domainStats['ICS/C2'].FAIL)`` / BLOCKED ``$($domainStats['ICS/C2'].BLOCKED)``
  - Security: PASS ``$($domainStats['Security'].PASS)`` / PENDING ``$($domainStats['Security'].PENDING)`` / FAIL ``$($domainStats['Security'].FAIL)`` / BLOCKED ``$($domainStats['Security'].BLOCKED)``
  - Deprecation: PASS ``$($domainStats['Deprecation'].PASS)`` / PENDING ``$($domainStats['Deprecation'].PENDING)`` / FAIL ``$($domainStats['Deprecation'].FAIL)`` / BLOCKED ``$($domainStats['Deprecation'].BLOCKED)``

---

## Requirements Table (Hard Format)

### Domain: ICS/C2 (Disaster / Association Ops)
| ReqID | Requirement | Source | Tasks | Commit | Evidence Paths | Status | Notes |
|---|---|---|---|---|---|---|---|
| ICS-C2-001 | SITREP/IAP generation is supported and reproducible | ``01-gap-analysis.md#GAP-A-M1`` | ``T2`` | ``de44a7a`` | ``E1: backend/src/.../command-chain.service.ts`` | ⏳ PENDING | Code exists (E1) but missing E2/E3 (runtime/test). |
| ICS-C2-002 | Map-based dispatch supports GPS + task assignment + audit trail | ``02-integration-map.md`` | ``T2,T5`` | ``d51fd8f`` | ``E1: backend/src/.../task-event.listeners.ts`` | ⏳ PENDING | Requires E2 dispatch flow log + E3 scenario test. |
| ICS-C2-003 | Command chain modeling with 17 ICS roles | ``01-gap-analysis.md#GAP-A-M3`` | ``T2`` | ``de44a7a`` | ``E1: backend/src/.../command-chain.entity.ts`` | ⏳ PENDING | Data model exists; needs verification evidence. |

### Domain: Security & Governance
| ReqID | Requirement | Source | Tasks | Commit | Evidence Paths | Status | Notes |
|---|---|---|---|---|---|---|---|
| SEC-PUB-001 | Public surface is allowlisted by SSOT policy and strict validator | ``docs/policy/public-surface.policy.json`` | ``T7`` | ``341c111`` | ``docs/proof/security/public-surface-check-report.json; docs/proof/security/public-surface.md`` | 🔴 BLOCKED | Strict blocked due to UnprotectedNotAllowlistedProd>0. |
| SEC-PUB-002 | Unprotected routes not allowlisted in production is zero | ``docs/proof/security/T1-routes-guards-mapping.json`` | ``T1,T7`` | ``440f016`` | ``docs/proof/gates/gate-summary.json`` | ⏳ PENDING | Must reach UnprotectedNotAllowlistedProd==0 to pass. |
| SEC-SMK-001 | Smoke tests verify public/auth/sensitive endpoints end-to-end | ``.github/workflows/audit-gates.yml`` | ``T7a`` | ``30aeae9`` | ``docs/proof/logs/T7a-smoke-tests.txt`` | 🔴 BLOCKED | Backend runtime evidence missing. |
| SEC-GUARD-001 | Guard coverage is tracked and reported via gate-summary | ``04-security-and-governance.md`` | ``T1`` | ``440f016`` | ``docs/proof/security/T1-routes-guards-mapping.json; docs/proof/gates/gate-summary.json`` | ✅ PASS | CoverageProd tracked in gate-summary.json. |

### Domain: Deprecation & Cleanup
| ReqID | Requirement | Source | Tasks | Commit | Evidence Paths | Status | Notes |
|---|---|---|---|---|---|---|---|
| DEPR-001 | Stub modules removed or excluded from production build | ``03-deprecation-cleanup.md`` | ``T8`` | ``630430e`` | ``docs/proof/gates/gate-summary.json; backend/src/app.module.ts`` | ✅ PASS | gate-summary shows StubModulesDisabled=true. |

---

## Row Rules (Hard)
1) **Source** must be a stable file reference + anchor (or section name).
2) **Tasks** must reference Task IDs in ``docs/proof/index.md``.
3) **Commit** must be a real git SHA (no placeholders in PASS rows).
4) **Evidence Paths**:
   - PASS rows must include at least one machine artifact under ``docs/proof/**`` (E2/E3).
   - E1-only (code path) is allowed only for PENDING/IMPLEMENTED states.
5) Summary must equal computed counts from this table; any mismatch should fail CI.

---

## Detailed Evidence Links (Optional)
- Gate Summary: [gate-summary.json](gates/gate-summary.json)
- Public Surface Inventory: [public-surface.md](security/public-surface.md)
- Public Surface Report: [public-surface-check-report.json](security/public-surface-check-report.json)
- Route Mapping: [T1-routes-guards-mapping.json](security/T1-routes-guards-mapping.json)

---

## Manual Notes (Allowed, non-authoritative)
- 2026-01-14: Auto-generated RTM with hard-evidence semantics (PASS requires E2/E3).
- 2026-01-13: ICS/C2 functional features require runtime scenarios before PASS.

---

**Last Updated**: $timestamp
"@

# Write output
$traceabilityContent | Out-File -FilePath $TraceabilityPath -Encoding utf8 -Force

Write-Host ""
Write-Host "✅ Generated: $TraceabilityPath" -ForegroundColor Green
Write-Host "   Summary: $totalReqs reqs (PASS=$($totals.PASS), PENDING=$($totals.PENDING), BLOCKED=$($totals.BLOCKED))" -ForegroundColor DarkGray
Write-Host ""
