/**
 * Baseline Scan Script (PowerShell version)
 * 
 * Purpose: Generate reproducible baseline counts for modules and pages
 * Output: JSON summary + text lists in /docs/proof/logs/
 * 
 * Usage: pwsh tools/audit/scan-baseline.ps1
 */

param(
    [string]$RootDir = (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
)

$ErrorActionPreference = "Stop"

# Paths
$BackendSrc = Join-Path $RootDir "backend\src"
$FrontendPages = Join-Path $RootDir "web-dashboard\src\pages"
$OutputDir = Join-Path $RootDir "docs\proof\logs"

# Ensure output directory exists
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
}

Write-Host "🔍 Starting baseline scan..." -ForegroundColor Cyan
Write-Host "   Root: $RootDir"
Write-Host "   Backend: $BackendSrc"
Write-Host "   Frontend: $FrontendPages"
Write-Host ""

# Count backend modules
Write-Host "📦 Scanning backend modules..." -ForegroundColor Yellow
$moduleFiles = Get-ChildItem -Path $BackendSrc -Recurse -Filter "*.module.ts" -File |
    Where-Object { 
        $_.FullName -notmatch "\\(node_modules|dist|test|mock|deprecated)\\" -and
        $_.Name -notmatch "\.(spec|test|mock)\."
    }

$moduleBreakdown = @{}
foreach ($module in $moduleFiles) {
    $relativePath = $module.FullName.Substring($BackendSrc.Length + 1)
    if ($relativePath -match "^([^\\]+)\\") {
        $category = $matches[1]
    } else {
        $category = "root"
    }
    if (-not $moduleBreakdown.ContainsKey($category)) {
        $moduleBreakdown[$category] = 0
    }
    $moduleBreakdown[$category]++
}

$moduleItems = $moduleFiles | ForEach-Object {
    $_.FullName.Substring($RootDir.Length + 1).Replace("\", "/")
}

Write-Host "   Found: $($moduleFiles.Count) modules" -ForegroundColor Green

# Count frontend pages
Write-Host "📄 Scanning frontend pages..." -ForegroundColor Yellow
$pageFiles = Get-ChildItem -Path $FrontendPages -Recurse -Filter "*.tsx" -File |
    Where-Object {
        $_.FullName -notmatch "\\(node_modules|dist|test|mock|deprecated|components)\\" -and
        $_.Name -notmatch "\.(spec|test|mock|stories|deprecated)\." -and
        $_.Name -notmatch "\.css$" -and
        $_.Name -notmatch "\.module\.css$"
    }

$pageBreakdown = @{}
foreach ($page in $pageFiles) {
    $relativePath = $page.FullName.Substring($FrontendPages.Length + 1)
    if ($relativePath -match "^([^\\]+)\\") {
        $category = $matches[1]
    } else {
        $category = "root"
    }
    if (-not $pageBreakdown.ContainsKey($category)) {
        $pageBreakdown[$category] = 0
    }
    $pageBreakdown[$category]++
}

$pageItems = $pageFiles | ForEach-Object {
    $_.FullName.Substring($RootDir.Length + 1).Replace("\", "/")
}

Write-Host "   Found: $($pageFiles.Count) pages" -ForegroundColor Green

# Build summary object
$timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss.fffZ")

$summary = @{
    version = "1.0.0"
    generated_at = $timestamp
    generated_by = "scan-baseline.ps1"
    spec_version = "baseline-counting-spec.md@v1"
    counts = @{
        backend_modules = @{
            total = $moduleFiles.Count
            breakdown = $moduleBreakdown
            list_file = "T0-modules-list.txt"
            items = @($moduleItems)
        }
        frontend_pages = @{
            total = $pageFiles.Count
            breakdown = $pageBreakdown
            list_file = "T0-pages-list.txt"
            items = @($pageItems)
        }
        api_routes = @{
            total = 0
            note = "Generated by scan-routes-guards.ts"
        }
    }
    exclusions_applied = @(
        "node_modules",
        "dist",
        "test",
        "mock",
        "deprecated",
        "*.spec.ts",
        "*.test.ts(x)",
        "*.mock.ts",
        "*.stories.tsx",
        "*.deprecated.*"
    )
}

# Write JSON summary
$summaryJson = $summary | ConvertTo-Json -Depth 10
$summaryPath = Join-Path $OutputDir "T0-count-summary.json"
$summaryJson | Out-File -FilePath $summaryPath -Encoding utf8
Write-Host "✅ Written: $summaryPath" -ForegroundColor Green

# Write modules list
$modulesPath = Join-Path $OutputDir "T0-modules-list.txt"
$moduleItems -join "`n" | Out-File -FilePath $modulesPath -Encoding utf8
Write-Host "✅ Written: $modulesPath" -ForegroundColor Green

# Write pages list
$pagesPath = Join-Path $OutputDir "T0-pages-list.txt"
$pageItems -join "`n" | Out-File -FilePath $pagesPath -Encoding utf8
Write-Host "✅ Written: $pagesPath" -ForegroundColor Green

# Write scan log
$logContent = @"
Baseline Scan Report
====================
Generated: $timestamp
Script: scan-baseline.ps1
Spec Version: baseline-counting-spec.md@v1

BACKEND MODULES
---------------
Total: $($moduleFiles.Count)
Breakdown:
$($moduleBreakdown.GetEnumerator() | ForEach-Object { "  - $($_.Key): $($_.Value)" } | Out-String)

FRONTEND PAGES
--------------
Total: $($pageFiles.Count)
Breakdown:
$($pageBreakdown.GetEnumerator() | ForEach-Object { "  - $($_.Key): $($_.Value)" } | Out-String)

EXCLUSIONS APPLIED
------------------
  - node_modules
  - dist
  - test
  - mock
  - deprecated
  - *.spec.ts
  - *.test.ts(x)
  - *.mock.ts
  - *.stories.tsx
  - *.deprecated.*
"@

$logPath = Join-Path $OutputDir "T0-baseline-scan.txt"
$logContent | Out-File -FilePath $logPath -Encoding utf8
Write-Host "✅ Written: $logPath" -ForegroundColor Green

Write-Host ""
Write-Host "📊 Summary:" -ForegroundColor Cyan
Write-Host "   Backend Modules: $($moduleFiles.Count)"
Write-Host "   Frontend Pages: $($pageFiles.Count)"
Write-Host ""
Write-Host "✅ Baseline scan complete!" -ForegroundColor Green
