#!/usr/bin/env ts-node
/**
 * Baseline Scan Script
 * 
 * Purpose: Generate reproducible baseline counts for modules, pages, and routes
 * Output: JSON summary + text lists in /docs/proof/logs/
 * 
 * Usage: npx ts-node tools/audit/scan-baseline.ts
 */

import * as fs from 'fs';
import * as path from 'path';

// Configuration
const ROOT_DIR = path.resolve(__dirname, '../..');
const BACKEND_SRC = path.join(ROOT_DIR, 'backend/src');
const FRONTEND_PAGES = path.join(ROOT_DIR, 'web-dashboard/src/pages');
const OUTPUT_DIR = path.join(ROOT_DIR, 'docs/proof/logs');

// Exclusion patterns
const EXCLUSIONS = {
    directories: ['node_modules', 'dist', 'test', 'mock', 'deprecated', '.git'],
    filePatterns: [/\.spec\.ts$/, /\.test\.tsx?$/, /\.mock\.ts$/, /\.stories\.tsx$/, /\.deprecated\./]
};

interface CountResult {
    total: number;
    breakdown: Record<string, number>;
    items: string[];
}

interface BaselineSummary {
    version: string;
    generated_at: string;
    generated_by: string;
    spec_version: string;
    counts: {
        backend_modules: CountResult & { list_file: string };
        frontend_pages: CountResult & { list_file: string };
        api_routes: { total: number; note: string };
    };
    exclusions_applied: string[];
}

/**
 * Recursively find files matching pattern
 */
function findFiles(
    dir: string,
    pattern: RegExp,
    excludeDirs: string[] = EXCLUSIONS.directories,
    excludePatterns: RegExp[] = EXCLUSIONS.filePatterns
): string[] {
    const results: string[] = [];

    if (!fs.existsSync(dir)) {
        console.warn(`Directory not found: ${dir}`);
        return results;
    }

    const items = fs.readdirSync(dir, { withFileTypes: true });

    for (const item of items) {
        const fullPath = path.join(dir, item.name);

        if (item.isDirectory()) {
            if (!excludeDirs.includes(item.name)) {
                results.push(...findFiles(fullPath, pattern, excludeDirs, excludePatterns));
            }
        } else if (item.isFile()) {
            const isExcluded = excludePatterns.some(p => p.test(item.name));
            if (!isExcluded && pattern.test(item.name)) {
                results.push(fullPath);
            }
        }
    }

    return results;
}

/**
 * Count backend modules
 */
function countBackendModules(): CountResult {
    const modulePattern = /\.module\.ts$/;
    const modules = findFiles(BACKEND_SRC, modulePattern);

    const breakdown: Record<string, number> = {};

    for (const modulePath of modules) {
        const relative = path.relative(BACKEND_SRC, modulePath);
        const category = relative.includes(path.sep)
            ? relative.split(path.sep)[0]
            : 'root';
        breakdown[category] = (breakdown[category] || 0) + 1;
    }

    return {
        total: modules.length,
        breakdown,
        items: modules.map(m => path.relative(ROOT_DIR, m).replace(/\\/g, '/'))
    };
}

/**
 * Count frontend pages
 */
function countFrontendPages(): CountResult {
    const pagePattern = /\.tsx$/;
    const excludePatterns = [
        ...EXCLUSIONS.filePatterns,
        /\.css$/,
        /\.module\.css$/
    ];

    const pages = findFiles(FRONTEND_PAGES, pagePattern, EXCLUSIONS.directories, excludePatterns);

    const breakdown: Record<string, number> = {};

    for (const pagePath of pages) {
        const relative = path.relative(FRONTEND_PAGES, pagePath);
        const category = relative.includes(path.sep)
            ? relative.split(path.sep)[0]
            : 'root';
        breakdown[category] = (breakdown[category] || 0) + 1;
    }

    return {
        total: pages.length,
        breakdown,
        items: pages.map(p => path.relative(ROOT_DIR, p).replace(/\\/g, '/'))
    };
}

/**
 * Generate baseline summary
 */
function generateBaseline(): BaselineSummary {
    const backendModules = countBackendModules();
    const frontendPages = countFrontendPages();

    return {
        version: '1.0.0',
        generated_at: new Date().toISOString(),
        generated_by: 'scan-baseline.ts',
        spec_version: 'baseline-counting-spec.md@v1',
        counts: {
            backend_modules: {
                ...backendModules,
                list_file: 'T0-modules-list.txt'
            },
            frontend_pages: {
                ...frontendPages,
                list_file: 'T0-pages-list.txt'
            },
            api_routes: {
                total: 0,
                note: 'Generated by scan-routes-guards.ts'
            }
        },
        exclusions_applied: [
            ...EXCLUSIONS.directories,
            ...EXCLUSIONS.filePatterns.map(p => p.toString())
        ]
    };
}

/**
 * Write output files
 */
function writeOutputs(summary: BaselineSummary): void {
    // Ensure output directory exists
    if (!fs.existsSync(OUTPUT_DIR)) {
        fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    }

    // Write summary JSON
    const summaryPath = path.join(OUTPUT_DIR, 'T0-count-summary.json');
    fs.writeFileSync(summaryPath, JSON.stringify(summary, null, 2), 'utf8');
    console.log(`✅ Written: ${summaryPath}`);

    // Write modules list
    const modulesPath = path.join(OUTPUT_DIR, 'T0-modules-list.txt');
    fs.writeFileSync(
        modulesPath,
        summary.counts.backend_modules.items.join('\n') + '\n',
        'utf8'
    );
    console.log(`✅ Written: ${modulesPath}`);

    // Write pages list
    const pagesPath = path.join(OUTPUT_DIR, 'T0-pages-list.txt');
    fs.writeFileSync(
        pagesPath,
        summary.counts.frontend_pages.items.join('\n') + '\n',
        'utf8'
    );
    console.log(`✅ Written: ${pagesPath}`);

    // Write scan log
    const logPath = path.join(OUTPUT_DIR, 'T0-baseline-scan.txt');
    const logContent = `
Baseline Scan Report
====================
Generated: ${summary.generated_at}
Script: ${summary.generated_by}
Spec Version: ${summary.spec_version}

BACKEND MODULES
---------------
Total: ${summary.counts.backend_modules.total}
Breakdown:
${Object.entries(summary.counts.backend_modules.breakdown)
            .map(([k, v]) => `  - ${k}: ${v}`)
            .join('\n')}

FRONTEND PAGES
--------------
Total: ${summary.counts.frontend_pages.total}
Breakdown:
${Object.entries(summary.counts.frontend_pages.breakdown)
            .map(([k, v]) => `  - ${k}: ${v}`)
            .join('\n')}

EXCLUSIONS APPLIED
------------------
${summary.exclusions_applied.map(e => `  - ${e}`).join('\n')}
`.trim();

    fs.writeFileSync(logPath, logContent, 'utf8');
    console.log(`✅ Written: ${logPath}`);
}

/**
 * Main execution
 */
function main(): void {
    console.log('🔍 Starting baseline scan...');
    console.log(`   Root: ${ROOT_DIR}`);
    console.log(`   Backend: ${BACKEND_SRC}`);
    console.log(`   Frontend: ${FRONTEND_PAGES}`);
    console.log('');

    const summary = generateBaseline();
    writeOutputs(summary);

    console.log('');
    console.log('📊 Summary:');
    console.log(`   Backend Modules: ${summary.counts.backend_modules.total}`);
    console.log(`   Frontend Pages: ${summary.counts.frontend_pages.total}`);
    console.log('');
    console.log('✅ Baseline scan complete!');
}

main();
